update comment

diff --git a/shadowsocks-go-debian b/shadowsocks-go-debian
--- a/shadowsocks-go-debian
+++ b/shadowsocks-go-debian
@@ -21,11 +21,11 @@ RET_VAL=0
 
 [ -x $BIN ] || exit 0
 
-if [[ ! -d $PID_DIR ]]; then
+if [ ! -d $PID_DIR ]; then
     mkdir -p $PID_DIR
     if [ $? -ne 0 ]; then
         echo "Creating PID directory $PID_DIR failed"
-        RET_VAL=1
+        exit 1
     fi
 fi
 
@@ -35,9 +35,9 @@ if [ ! -f $CONF ]; then
 fi
 
 check_running() {
-    if [[ -r $PID_FILE ]]; then
+    if [ -r $PID_FILE ]; then
         read PID < $PID_FILE
-        if [[ -d "/proc/$PID" ]]; then
+        if [ -d "/proc/$PID" ]; then
             return 0
         else
             rm -f $PID_FILE
@@ -52,10 +52,10 @@ do_status() {
     check_running
     case $? in
         0)
-        echo "$NAME is running with PID $PID"
+        echo "$NAME (pid $PID) is running..."
         ;;
         1|2)
-        echo "$NAME is not running"
+        echo "$NAME is stopped"
         RET_VAL=1
         ;;
     esac
@@ -63,7 +63,7 @@ do_status() {
 
 do_start() {
     if check_running; then
-        echo "$NAME is already running with PID $PID"
+        echo "$NAME (pid $PID) is already running..."
         return 0
     fi
     $BIN -c $CONF 2>&1 > /dev/null &
@@ -71,9 +71,9 @@ do_start() {
     echo $PID > $PID_FILE
     sleep 0.3
     if check_running; then
-        echo "$NAME start success"
+        echo "Starting $NAME success"
     else
-        echo "$NAME start failed"
+        echo "Starting $NAME failed"
         RET_VAL=1
     fi
 }
@@ -82,9 +82,9 @@ do_stop() {
     if check_running; then
         kill -9 $PID
         rm -f $PID_FILE
-        echo "$NAME stop success"
+        echo "Stopping $NAME success"
     else
-        echo "$NAME is not running"
+        echo "$NAME is stopped"
         RET_VAL=1
     fi
 }
